apiVersion: v1
kind: Pod
metadata:
  name: shiftweek-cluster-sizer
  namespace: default
spec:
  initContainers:
  - name: fake-data-generator 
    image: quay.io/jkyros/shiftweek-11-2023:autoscaler-predictor-model
    volumeMounts:
    - name: data
      mountPath: /usr/src/app/data
    command: ["python","synthesizeData.py"]
    imagePullPolicy: Always
  containers:
  - name: predictive-cluster-sizer 
    image: quay.io/jkyros/shiftweek-11-2023:predictive-cluster-sizer
    volumeMounts:
    - name: data
      mountPath: /data
    command: ["./predictive-cluster-sizer"]
    args: [""]
    imagePullPolicy: Always
  - name: autoscaler-predictor-model
    image: quay.io/jkyros/shiftweek-11-2023:autoscaler-predictor-model
    ports:
    - containerPort: 5001
    imagePullPolicy: Always
  volumes:
  - name: data
    emptyDir: {}
---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: predictive-cluster-sizer
  rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["machine.openshift.io"]
    resources: ["machinesets"]
    verbs: ["get","watch","list","update","patch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get","watch","list"]
---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: predictive-cluster-sizer
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
  roleRef:
    kind: ClusterRole
    name: predictive-cluster-sizer
    apiGroup: rbac.authorization.k8s.io
